# Generated by Django 3.2.4 on 2021-11-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20211101_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='clothes', max_length=50),
        ),
    ]
